export default defineEventHandler(async (event) => {
  try {
    if (event.method === 'GET') {
      const menuList = [
        {
          id: 1,
          homepageType: 'ADMIN',
          menuName: '교육계획/분석/설계',
          parentMenuId: null,
          menuUrl: null,
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: true,
          menuIcon: 'pencil',
          isDeleted: false,
          createdDate: '2025-07-14T13:00:59',
          lastModifiedDate: '2025-07-14T13:02:02',
          _children: [
            {
              id: 3,
              homepageType: 'ADMIN',
              menuName: '교육요청 관리',
              parentMenuId: 1,
              menuUrl: '/education/education-plan/education-request/regist',
              menuDepth: 2,
              menuOrder: 1,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 23,
                  homepageType: 'ADMIN',
                  menuName: '교육요청 등록',
                  parentMenuId: 3,
                  menuUrl:
                    '/education/education-plan/education-request/regist/insert',
                  menuDepth: 4,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-08-07T13:32:40',
                  lastModifiedDate: '2025-08-07T13:32:40',
                },
                {
                  id: 25,
                  homepageType: 'ADMIN',
                  menuName: '교육요청 상세',
                  parentMenuId: 3,
                  menuUrl:
                    '/education/education-plan/education-request/regist/[id]',
                  menuDepth: 4,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-08-07T13:32:40',
                  lastModifiedDate: '2025-08-07T13:32:40',
                },
              ],
            },
            // {
            //   id: 2,
            //   homepageType: 'ADMIN',
            //   menuName: '교육요청 관리',
            //   parentMenuId: 1,
            //   menuUrl: null,
            //   menuDepth: 2,
            //   menuOrder: 0,
            //   isActive: true,
            //   requireLogin: true,
            //   menuType: 'FOLDER',
            //   isNavigation: true,
            //   menuIcon: null,
            //   isDeleted: false,
            //   createdDate: '2025-07-14T13:10:40',
            //   lastModifiedDate: '2025-07-17T08:54:55',
            //   _children: [
            //     {
            //       id: 3,
            //       homepageType: 'ADMIN',
            //       menuName: '교육요청 관리',
            //       parentMenuId: 2,
            //       menuUrl: '/education/education-plan/education-request/regist',
            //       menuDepth: 3,
            //       menuOrder: 2,
            //       isActive: true,
            //       requireLogin: true,
            //       menuType: 'PAGE',
            //       isNavigation: true,
            //       menuIcon: 'document',
            //       isDeleted: false,
            //       createdDate: '2025-07-14T13:10:40',
            //       lastModifiedDate: '2025-07-17T08:54:55',
            //       _children: [
            //         {
            //           id: 23,
            //           homepageType: 'ADMIN',
            //           menuName: '교육요청 등록',
            //           parentMenuId: 3,
            //           menuUrl: '/education/education-plan/education-request/regist/insert',
            //           menuDepth: 4,
            //           menuOrder: 0,
            //           isActive: true,
            //           requireLogin: true,
            //           menuType: 'PAGE',
            //           isNavigation: false,
            //           menuIcon: 'document',
            //           isDeleted: false,
            //           createdDate: '2025-08-07T13:32:40',
            //           lastModifiedDate: '2025-08-07T13:32:40',
            //         },
            //         {
            //           id: 25,
            //           homepageType: 'ADMIN',
            //           menuName: '교육요청 상세',
            //           parentMenuId: 3,
            //           menuUrl: '/education/education-plan/education-request/regist/[id]',
            //           menuDepth: 4,
            //           menuOrder: 0,
            //           isActive: true,
            //           requireLogin: true,
            //           menuType: 'PAGE',
            //           isNavigation: false,
            //           menuIcon: 'document',
            //           isDeleted: false,
            //           createdDate: '2025-08-07T13:32:40',
            //           lastModifiedDate: '2025-08-07T13:32:40',
            //         },
            //       ],
            //     },
            //     {
            //       id: 4,
            //       homepageType: 'ADMIN',
            //       menuName: '소위원회결과검토',
            //       parentMenuId: 2,
            //       menuUrl:
            //         '/education/education-plan/education-request/subcommittee-result',
            //       menuDepth: 3,
            //       menuOrder: 2,
            //       isActive: true,
            //       requireLogin: true,
            //       menuType: 'PAGE',
            //       isNavigation: true,
            //       menuIcon: 'document',
            //       isDeleted: false,
            //       createdDate: '2025-07-14T13:10:40',
            //       lastModifiedDate: '2025-07-17T08:54:55',
            //       _children: [
            //         {
            //           id: 5,
            //           homepageType: 'ADMIN',
            //           menuName: '소위원회결과검토 상세',
            //           parentMenuId: 4,
            //           menuUrl: '/education/education-plan/education-request/subcommittee-result/[id]',
            //           menuDepth: 4,
            //           menuOrder: 0,
            //           isActive: true,
            //           requireLogin: true,
            //           menuType: 'PAGE',
            //           isNavigation: false,
            //           menuIcon: 'document',
            //           isDeleted: false,
            //           createdDate: '2025-08-07T13:32:40',
            //           lastModifiedDate: '2025-08-07T13:32:40',
            //         },
            //       ],
            //     },
            //   ],
            // },
            // {
            //   id: 6,
            //   homepageType: 'ADMIN',
            //   menuName: '분석(FGW)',
            //   parentMenuId: 1,
            //   menuUrl: null,
            //   menuDepth: 2,
            //   menuOrder: 0,
            //   isActive: true,
            //   requireLogin: true,
            //   menuType: 'FOLDER',
            //   isNavigation: true,
            //   menuIcon: null,
            //   isDeleted: false,
            //   createdDate: '2025-07-14T13:10:40',
            //   lastModifiedDate: '2025-07-17T08:54:55',
            //   _children: [
            //     {
            //       id: 7,
            //       homepageType: 'ADMIN',
            //       menuName: '분석2단계',
            //       parentMenuId: 5,
            //       menuUrl: null,
            //       menuDepth: 3,
            //       menuOrder: 2,
            //       isActive: true,
            //       requireLogin: true,
            //       menuType: 'PAGE',
            //       isNavigation: true,
            //       menuIcon: 'document',
            //       isDeleted: false,
            //       createdDate: '2025-07-14T13:10:40',
            //       lastModifiedDate: '2025-07-17T08:54:55',
            //     },
            //     {
            //       id: 8,
            //       homepageType: 'ADMIN',
            //       menuName: '분석3단계',
            //       parentMenuId: 5,
            //       menuUrl: null,
            //       menuDepth: 3,
            //       menuOrder: 2,
            //       isActive: true,
            //       requireLogin: true,
            //       menuType: 'PAGE',
            //       isNavigation: true,
            //       menuIcon: null,
            //       isDeleted: false,
            //       createdDate: '2025-07-14T13:10:40',
            //       lastModifiedDate: '2025-07-17T08:54:55',
            //     },
            //   ],
            // },
            {
              id: 9,
              homepageType: 'ADMIN',
              menuName: '교육기준정보설계',
              parentMenuId: 1,
              menuUrl: '/education/education-plan/ttm',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 10,
                  homepageType: 'ADMIN',
                  menuName: '교육기준정보 엑셀업로드',
                  parentMenuId: 9,
                  menuUrl: '/education/education-plan/ttm/excel-upload',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 10,
              homepageType: 'ADMIN',
              menuName: '시행계획서 관리',
              parentMenuId: 1,
              menuUrl: '/education/education-plan/execution-plan',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 11,
                  homepageType: 'ADMIN',
                  menuName: '시행계획서관리 상세',
                  parentMenuId: 10,
                  menuUrl:
                    '/education/education-plan/execution-plan/detail/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-08-07T13:32:40',
                  lastModifiedDate: '2025-08-07T13:32:40',
                },
                {
                  id: 25,
                  homepageType: 'ADMIN',
                  menuName: '시행계획서관리 등록',
                  parentMenuId: 10,
                  menuUrl:
                    '/education/education-plan/execution-plan/detail/create',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-08-07T13:32:40',
                  lastModifiedDate: '2025-08-07T13:32:40',
                },
              ],
            },
            {
              id: 12,
              homepageType: 'ADMIN',
              menuName: '심의',
              parentMenuId: 1,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 13,
                  homepageType: 'ADMIN',
                  menuName: '심의생성',
                  parentMenuId: 11,
                  menuUrl: '/education/education-plan/review/create',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 14,
                  homepageType: 'ADMIN',
                  menuName: '심의관리',
                  parentMenuId: 11,
                  menuUrl: '/education/education-plan/review/regist',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 18,
                      homepageType: 'ADMIN',
                      menuName: '심의관리 상세',
                      parentMenuId: 15,
                      menuUrl: '/education/education-plan/review/regist/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'pencil',
                      isDeleted: false,
                      createdDate: '2025-08-07T13:32:40',
                      lastModifiedDate: '2025-08-07T13:32:40',
                    },
                  ],
                },
                // {
                //   id: 15,
                //   homepageType: 'ADMIN',
                //   menuName: '심의위원 결과제출',
                //   parentMenuId: 11,
                //   menuUrl:'/education/education-plan/review/result',
                //   menuDepth: 3,
                //   menuOrder: 2,
                //   isActive: true,
                //   requireLogin: true,
                //   menuType: 'PAGE',
                //   isNavigation: true,
                //   menuIcon: 'pencil',
                //   isDeleted: false,
                //   createdDate: '2025-07-14T13:10:40',
                //   lastModifiedDate: '2025-07-17T08:54:55',
                //   _children: [
                //     {
                //       id: 24,
                //       homepageType: 'ADMIN',
                //       menuName: '심의위원 결과제출 상세',
                //       parentMenuId: 15,
                //       menuUrl: '/education/education-plan/review/result/[id]',
                //       menuDepth: 4,
                //       menuOrder: 0,
                //       isActive: true,
                //       requireLogin: true,
                //       menuType: 'PAGE',
                //       isNavigation: false,
                //       menuIcon: 'pencil',
                //       isDeleted: false,
                //       createdDate: '2025-08-07T13:32:40',
                //       lastModifiedDate: '2025-08-07T13:32:40',
                //     },
                //   ],
                // },
                {
                  id: 16,
                  homepageType: 'ADMIN',
                  menuName: '심의안건종합',
                  parentMenuId: 11,
                  menuUrl: '/education/education-plan/review/agenda',
                  menuDepth: 3,
                  menuOrder: 3,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 441,
              homepageType: 'ADMIN',
              menuName: '연간교육일정',
              parentMenuId: 1,
              menuUrl: '/education/education-plan/annual-schedule',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [],
            },
          ],
        },
        {
          id: 442,
          homepageType: 'ADMIN',
          menuName: '교육운영',
          parentMenuId: null,
          menuUrl: null,
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: true,
          menuIcon: 'book-open',
          isDeleted: false,
          createdDate: '2025-07-14T13:00:59',
          lastModifiedDate: '2025-07-14T13:02:02',
          _children: [
            {
              id: 2002,
              homepageType: 'ADMIN',
              menuName: '과정개설',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 2110,
                  homepageType: 'ADMIN',
                  menuName: '운영과정개설관리',
                  parentMenuId: 443,
                  menuUrl:
                    '/education/operation/course-opening/opening-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 2111,
                      homepageType: 'ADMIN',
                      menuName: '운영과정개설관리 상세',
                      parentMenuId: 449,
                      menuUrl:
                        '/education/operation/course-opening/opening-management/detail/[id]',
                      menuDepth: 4,
                      menuOrder: 1,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                    },
                  ],
                },
                {
                  id: 450,
                  homepageType: 'ADMIN',
                  menuName: '운영과정변경관리',
                  parentMenuId: 443,
                  menuUrl:
                    '/education/operation/course-opening/change-management',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 451,
                  homepageType: 'ADMIN',
                  menuName: '변경확정처리',
                  parentMenuId: 443,
                  menuUrl:
                    '/education/operation/course-opening/change-confirmation-processing',
                  menuDepth: 3,
                  menuOrder: 2,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 452,
                  homepageType: 'ADMIN',
                  menuName: '사번변환처리',
                  parentMenuId: 443,
                  menuUrl:
                    '/education/operation/course-opening/employee-id-conversion',
                  menuDepth: 3,
                  menuOrder: 3,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 444,
              homepageType: 'ADMIN',
              menuName: '과정준비',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 1,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 515,
                  homepageType: 'ADMIN',
                  menuName: '참가자관리',
                  parentMenuId: 444,
                  menuUrl:
                    '/education/operation/course-preparation/participant',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 516,
                      homepageType: 'ADMIN',
                      menuName: '분반관리',
                      parentMenuId: 515,
                      menuUrl:
                        '/education/operation/course-preparation/participant/class-division/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'book-open',
                      isDeleted: false,
                      createdDate: '2025-11-10T13:32:40',
                      lastModifiedDate: '2025-11-10T13:32:40',
                    },
                    {
                      id: 518,
                      homepageType: 'ADMIN',
                      menuName: '교육인원 관리',
                      parentMenuId: 515,
                      menuUrl:
                        '/education/operation/course-preparation/participant/trainee-management/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'book-open',
                      isDeleted: false,
                      createdDate: '2025-11-10T13:32:40',
                      lastModifiedDate: '2025-11-10T13:32:40',
                    },
                  ],
                },
                {
                  id: 999,
                  homepageType: 'ADMIN',
                  menuName: '강의실배정관리',
                  parentMenuId: 444,
                  menuUrl:
                    '/education/operation/course-preparation/classroom-allocation',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 999,
                  homepageType: 'ADMIN',
                  menuName: '생활실 배정관리',
                  parentMenuId: 444,
                  menuUrl:
                    '/education/operation/course-preparation/living-room-assignment',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 516,
                      homepageType: 'ADMIN',
                      menuName: '생활실배정관리 상세',
                      parentMenuId: 515,
                      menuUrl:
                        '/education/operation/course-preparation/living-room-assignment/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'book-open',
                      isDeleted: false,
                      createdDate: '2025-11-10T13:32:40',
                      lastModifiedDate: '2025-11-10T13:32:40',
                    },
                  ],
                },
                {
                  id: 2279,
                  homepageType: 'ADMIN',
                  menuName: '시간표관리',
                  parentMenuId: 444,
                  menuUrl:
                    '/education/operation/course-preparation/time-table-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 2281,
                      homepageType: 'ADMIN',
                      menuName: '시간표관리 상세',
                      parentMenuId: 2279,
                      menuUrl:
                        '/education/operation/course-preparation/time-table-management/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'book-open',
                      isDeleted: false,
                      createdDate: '2025-11-10T13:32:40',
                      lastModifiedDate: '2025-11-10T13:32:40',
                    },
                  ],
                },
                {
                  id: 2280,
                  homepageType: 'ADMIN',
                  menuName: '운영과정준비관리',
                  parentMenuId: 444,
                  menuUrl:
                    '/education/operation/course-preparation/preparation-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 445,
              homepageType: 'ADMIN',
              menuName: '과정진행',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 2,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 501,
                  homepageType: 'ADMIN',
                  menuName: '과정진행관리',
                  parentMenuId: 445,
                  menuUrl: '/education/operation/course-progress/management',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 501,
                      homepageType: 'ADMIN',
                      menuName: '성적 엑셀업로드',
                      parentMenuId: 2001,
                      menuUrl:
                        '/education/operation/course-progress/management/excel-upload/[id]',
                      menuDepth: 4,
                      menuOrder: 1,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
                {
                  id: 502,
                  homepageType: 'ADMIN',
                  menuName: '평가강의실배정관리',
                  parentMenuId: 445,
                  menuUrl:
                    '/education/operation/course-progress/evaluation-room-assignment',
                  menuDepth: 3,
                  menuOrder: 2,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 503,
                  homepageType: 'ADMIN',
                  menuName: '시험감독자배정현황',
                  parentMenuId: 445,
                  menuUrl:
                    '/education/operation/course-progress/exam-supervisor-assignment',
                  menuDepth: 3,
                  menuOrder: 3,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 504,
                  homepageType: 'ADMIN',
                  menuName: '대강당좌석배치관리',
                  parentMenuId: 445,
                  menuUrl:
                    '/education/operation/course-progress/auditorium-seat-management',
                  menuDepth: 3,
                  menuOrder: 4,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 505,
                  homepageType: 'ADMIN',
                  menuName: '주간교육현황',
                  parentMenuId: 445,
                  menuUrl:
                    '/education/operation/course-progress/weekly-education-status',
                  menuDepth: 3,
                  menuOrder: 5,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 506,
                  homepageType: 'ADMIN',
                  menuName: '주간시간표현황',
                  parentMenuId: 445,
                  menuUrl:
                    '/education/operation/course-progress/weekly-schedule-status',
                  menuDepth: 3,
                  menuOrder: 6,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 446,
              homepageType: 'ADMIN',
              menuName: '과정종료',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 3,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 507,
                  homepageType: 'ADMIN',
                  menuName: '과정별 수료처리현황',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/course-completion/process-status',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 510,
                      homepageType: 'ADMIN',
                      menuName: '과정별 수료처리 상세',
                      parentMenuId: 507,
                      menuUrl:
                        '/education/operation/course-completion/process-status/[id]',
                      menuDepth: 4,
                      menuOrder: 1,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                    },
                  ],
                },
                {
                  id: 508,
                  homepageType: 'ADMIN',
                  menuName: '과정별성적결과관리',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/course-completion/grade-result',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 509,
                      homepageType: 'ADMIN',
                      menuName: '과정별 성적결과관리 상세',
                      parentMenuId: 510,
                      menuUrl:
                        '/education/operation/course-completion/grade-result/[id]',
                      menuDepth: 4,
                      menuOrder: 1,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                    },
                  ],
                },
                {
                  id: 510,
                  homepageType: 'ADMIN',
                  menuName: '증명서발급현황',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/course-completion/certificate-issue',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 511,
                  homepageType: 'ADMIN',
                  menuName: '사내/외강사료계산',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/course-completion/instructor-fee',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 509,
                      homepageType: 'ADMIN',
                      menuName: '강사료 지급/확인',
                      parentMenuId: 511,
                      menuUrl:
                        '/education/operation/course-completion/instructor-fee/[id]',
                      menuDepth: 4,
                      menuOrder: 1,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: 'book-open',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                    },
                  ],
                },
              ],
            },
            {
              id: 447,
              homepageType: 'ADMIN',
              menuName: '직업훈련관리',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 4,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 448,
                  homepageType: 'ADMIN',
                  menuName: '훈련실시신고',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/vocational-training/commencement-report',
                  menuDepth: 2,
                  menuOrder: 5,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 453,
                  homepageType: 'ADMIN',
                  menuName: '변경신고',
                  parentMenuId: 442,
                  menuUrl:
                    '/education/operation/vocational-training/change-report',
                  menuDepth: 2,
                  menuOrder: 6,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 448,
              homepageType: 'ADMIN',
              menuName: '생활지도',
              parentMenuId: 442,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 5,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: 'book-open',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 509,
                  homepageType: 'ADMIN',
                  menuName: '생활지도관리',
                  parentMenuId: 448,
                  menuUrl: '/education/operation/guidance/management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 510,
                  homepageType: 'ADMIN',
                  menuName: '참가자외출외박관리',
                  parentMenuId: 448,
                  menuUrl: '/education/operation/guidance/participant-leave',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 511,
                  homepageType: 'ADMIN',
                  menuName: '교육경고장발급관리',
                  parentMenuId: 448,
                  menuUrl: '/education/operation/guidance/warning-issue',
                  menuDepth: 3,
                  menuOrder: 2,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 512,
                  homepageType: 'ADMIN',
                  menuName: '생활지도관리 상세',
                  parentMenuId: 448,
                  menuUrl: '/education/operation/guidance/management/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'book-open',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
          ],
        },
        {
          id: 331,
          homepageType: 'ADMIN',
          menuName: '교육기준',
          parentMenuId: null,
          menuUrl: null,
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: true,
          menuIcon: 'file-pencil',
          isDeleted: false,
          createdDate: '2025-07-14T13:00:59',
          lastModifiedDate: '2025-07-14T13:02:02',
          _children: [
            {
              id: 350,
              homepageType: 'ADMIN',
              menuName: '공통관리',
              parentMenuId: 331,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 351,
                  homepageType: 'ADMIN',
                  menuName: '조직정보',
                  parentMenuId: 350,
                  menuUrl: '/education/criteria/common/organization-info',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 352,
                  homepageType: 'ADMIN',
                  menuName: '메일템플릿관리',
                  parentMenuId: 350,
                  menuUrl:
                    '/education/criteria/common/mail-template-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 353,
                  homepageType: 'ADMIN',
                  menuName: '시험감독자관리',
                  parentMenuId: 350,
                  menuUrl:
                    '/education/criteria/common/exam-supervisor-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 354,
                  homepageType: 'ADMIN',
                  menuName: '사내강사료지급기준',
                  parentMenuId: 350,
                  menuUrl: '/education/criteria/common/instructor-fee-standard',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 353,
                      homepageType: 'ADMIN',
                      menuName: '사내강사료지급기준',
                      parentMenuId: 354,
                      menuUrl:
                        '/education/criteria/common/instructor-fee-standard/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: false,
                      menuIcon: 'pencil',
                      isDeleted: false,
                      createdDate: '2025-08-07T13:32:40',
                      lastModifiedDate: '2025-08-07T13:32:40',
                    },
                  ],
                },
              ],
            },
            {
              id: 332,
              homepageType: 'ADMIN',
              menuName: '시설관리',
              parentMenuId: 331,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 333,
                  homepageType: 'ADMIN',
                  menuName: '교육기관',
                  parentMenuId: 332,
                  menuUrl:
                    '/education/criteria/facility/education-organization',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 334,
                  homepageType: 'ADMIN',
                  menuName: '교육장소',
                  parentMenuId: 332,
                  menuUrl: '/education/criteria/facility/education-place',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 335,
                  homepageType: 'ADMIN',
                  menuName: '강의실정보',
                  parentMenuId: 332,
                  menuUrl: '/education/criteria/facility/lecture-room',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'file-pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 336,
                  homepageType: 'ADMIN',
                  menuName: '발전소 및 시뮬레이터 정보 관리',
                  parentMenuId: 332,
                  menuUrl:
                    '/education/criteria/facility/power-station-simulator',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 337,
                  homepageType: 'ADMIN',
                  menuName: '생활실정보',
                  parentMenuId: 332,
                  menuUrl: '/education/criteria/facility/residential-Info',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 338,
                  homepageType: 'ADMIN',
                  menuName: '수업시간관리',
                  parentMenuId: 332,
                  menuUrl: '/education/criteria/facility/class-time',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 339,
                  homepageType: 'ADMIN',
                  menuName: '휴일관리',
                  parentMenuId: 332,
                  menuUrl: '/education/criteria/facility/vacation-manage',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 341,
              homepageType: 'ADMIN',
              menuName: '강사관리',
              parentMenuId: 331,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 342,
                  homepageType: 'ADMIN',
                  menuName: '강사관리',
                  parentMenuId: 341,
                  menuUrl: '/education/criteria/instructor/management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 3421,
                      homepageType: 'ADMIN',
                      menuName: '강사등록',
                      parentMenuId: 342,
                      menuUrl:
                        '/education/criteria/instructor/management/register',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                    {
                      id: 3422,
                      homepageType: 'ADMIN',
                      menuName: '강사관리 상세',
                      parentMenuId: 342,
                      menuUrl:
                        '/education/criteria/instructor/management/internal/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                    {
                      id: 3423,
                      homepageType: 'ADMIN',
                      menuName: '강사관리 상세',
                      parentMenuId: 342,
                      menuUrl:
                        '/education/criteria/instructor/management/external/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: null,
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
                {
                  id: 343,
                  homepageType: 'ADMIN',
                  menuName: '교수,사내강사 선정대상 조회',
                  parentMenuId: 341,
                  menuUrl: '/education/criteria/instructor/internal-list',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 344,
                  homepageType: 'ADMIN',
                  menuName: '사외강사 선정대상 조회',
                  parentMenuId: 341,
                  menuUrl: '/education/criteria/instructor/external-list',
                  menuDepth: 3,
                  menuOrder: 1,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
          ],
        },
        {
          id: 400,
          homepageType: 'ADMIN',
          menuName: '만족도평가',
          parentMenuId: null,
          menuUrl: null,
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: true,
          menuIcon: 'file-ox',
          isDeleted: false,
          createdDate: '2025-07-14T13:00:59',
          lastModifiedDate: '2025-07-14T13:02:02',
          _children: [
            {
              id: 401,
              homepageType: 'ADMIN',
              menuName: '설문지관리',
              parentMenuId: 400,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: 'file-ox',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 402,
                  homepageType: 'ADMIN',
                  menuName: '설문지관리',
                  parentMenuId: 401,
                  menuUrl:
                    '/education/satisfaction-survey/questionnaire-management',
                  menuDepth: 2,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'FOLDER',
                  isNavigation: true,
                  menuIcon: 'file-ox',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 404,
                      homepageType: 'ADMIN',
                      menuName: '설문지관리 상세',
                      parentMenuId: 402,
                      menuUrl:
                        '/education/satisfaction-survey/questionnaire-management/[id]',
                      menuDepth: 2,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'FOLDER',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
                {
                  id: 403,
                  homepageType: 'ADMIN',
                  menuName: '설문문항관리',
                  parentMenuId: 401,
                  menuUrl:
                    '/education/satisfaction-survey/survey-item-management',
                  menuDepth: 2,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'FOLDER',
                  isNavigation: true,
                  menuIcon: 'file-ox',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 405,
                      homepageType: 'ADMIN',
                      menuName: '설문문항관리 상세',
                      parentMenuId: 403,
                      menuUrl:
                        '/education/satisfaction-survey/survey-item-management/[id]',
                      menuDepth: 2,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'FOLDER',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: 406,
              homepageType: 'ADMIN',
              menuName: '설문결과관리',
              parentMenuId: 400,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: 'file-ox',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 407,
                  homepageType: 'ADMIN',
                  menuName: '교과목설문결과',
                  parentMenuId: 406,
                  menuUrl:
                    '/education/satisfaction-survey/course-survey-result',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'file-ox',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 408,
                      homepageType: 'ADMIN',
                      menuName: '교육과정별 교과목설문종합',
                      parentMenuId: 407,
                      menuUrl:
                        '/education/satisfaction-survey/course-survey-result/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                    {
                      id: 409,
                      homepageType: 'ADMIN',
                      menuName: '교과목설문결과 상세',
                      parentMenuId: 407,
                      menuUrl:
                        '/education/satisfaction-survey/course-survey-result/detail/[id]',
                      menuDepth: 4,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'PAGE',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
                {
                  id: 407,
                  homepageType: 'ADMIN',
                  menuName: '과정설문결과 ',
                  parentMenuId: 406,
                  menuUrl:
                    '/education/satisfaction-survey/training-survey-result',
                  menuDepth: 2,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'file-ox',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 405,
                      homepageType: 'ADMIN',
                      menuName: '사전설문결과 ',
                      parentMenuId: 403,
                      menuUrl:
                        '/education/satisfaction-survey/training-survey-result/detail/pre',
                      menuDepth: 2,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'FOLDER',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                    {
                      id: 405,
                      homepageType: 'ADMIN',
                      menuName: '수료설문결과 ',
                      parentMenuId: 407,
                      menuUrl:
                        '/education/satisfaction-survey/training-survey-result/detail/completion',
                      menuDepth: 2,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'FOLDER',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
                {
                  id: 408,
                  homepageType: 'ADMIN',
                  menuName: '설문결과통계',
                  parentMenuId: 406,
                  menuUrl:
                    '/education/satisfaction-survey/survey-result-statistics',
                  menuDepth: 2,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'file-ox',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [
                    {
                      id: 405,
                      homepageType: 'ADMIN',
                      menuName: '과정분석상세 ',
                      parentMenuId: 408,
                      menuUrl:
                        '/education/satisfaction-survey/survey-result-statistics/[id]',
                      menuDepth: 2,
                      menuOrder: 0,
                      isActive: true,
                      requireLogin: true,
                      menuType: 'FOLDER',
                      isNavigation: true,
                      menuIcon: 'file-ox',
                      isDeleted: false,
                      createdDate: '2025-07-14T13:10:40',
                      lastModifiedDate: '2025-07-17T08:54:55',
                      _children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 81,
          homepageType: 'ADMIN',
          menuName: '공통시스템',
          parentMenuId: 1,
          menuUrl: '',
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: false,
          menuIcon: 'common-setting',
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [
            {
              id: 83,
              homepageType: 'ADMIN',
              menuName: '코드관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 84,
                  homepageType: 'ADMIN',
                  menuName: '공통코드관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/code',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 85,
              homepageType: 'ADMIN',
              menuName: '권한관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 86,
                  homepageType: 'ADMIN',
                  menuName: '사용자관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/authority/user',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 870,
                  homepageType: 'ADMIN',
                  menuName: '프로그램관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/authority/program',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 87,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹관리',
                  parentMenuId: 86,
                  menuUrl: '/education/system/authority/group/management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 88,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹별 프로그램관리',
                  parentMenuId: 86,
                  menuUrl:
                    '/education/system/authority/group/program-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 89,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹별 사용자관리',
                  parentMenuId: 86,
                  menuUrl: '/education/system/authority/group/user-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 90,
              homepageType: 'ADMIN',
              menuName: '기타관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              isNavigation: true,
              _children: [
                {
                  id: 91,
                  homepageType: 'ADMIN',
                  menuName: '직무별교육체계도 관리',
                  parentMenuId: 90,
                  menuUrl: '/education/system/etc/job-education-system',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 92,
                  homepageType: 'ADMIN',
                  menuName: '오시는길 관리',
                  parentMenuId: 90,
                  menuUrl: '/education/system/etc/edu-institution',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 91,
              homepageType: 'ADMIN',
              menuName: '배치관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              isNavigation: true,
              _children: [
                {
                  id: 91,
                  homepageType: 'ADMIN',
                  menuName: '배치프로그램관리',
                  parentMenuId: 91,
                  menuUrl: '/education/system/batch/program-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 92,
                  homepageType: 'ADMIN',
                  menuName: '배치결과',
                  parentMenuId: 91,
                  menuUrl: '/education/system/batch/result',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
          ],
        },
        {
          id: 80,
          homepageType: 'ADMIN',
          menuName: '게시판',
          parentMenuId: 1,
          menuUrl: '',
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: false,
          menuIcon: 'bubble-star',
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [
            {
              id: 18,
              homepageType: 'ADMIN',
              menuName: '공지사항',
              parentMenuId: 80,
              menuUrl: '/education/board/notice',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 512,
                  homepageType: 'ADMIN',
                  menuName: '공지사항 상세',
                  parentMenuId: 18,
                  menuUrl: '/education/board/notice/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 513,
                  homepageType: 'ADMIN',
                  menuName: '공지사항 등록  ',
                  parentMenuId: 18,
                  menuUrl: '/education/board/notice/add',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 514,
                  homepageType: 'ADMIN',
                  menuName: '공지사항 수정  ',
                  parentMenuId: 18,
                  menuUrl: '/education/board/notice/edit/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 94,
              homepageType: 'ADMIN',
              menuName: '팝업공지관리',
              parentMenuId: 80,
              menuUrl: '/education/board/popup-notice',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 95,
                  homepageType: 'ADMIN',
                  menuName: '팝업공지 등록  ',
                  parentMenuId: 94,
                  menuUrl: '/education/board/popup-notice/add',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 96,
                  homepageType: 'ADMIN',
                  menuName: '팝업공지 수정  ',
                  parentMenuId: 94,
                  menuUrl: '/education/board/popup-notice/edit/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 93,
              homepageType: 'ADMIN',
              menuName: 'Q&A',
              parentMenuId: 80,
              menuUrl: '/education/board/qa',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 515,
                  homepageType: 'ADMIN',
                  menuName: 'Q&A 상세',
                  parentMenuId: 93,
                  menuUrl: '/education/board/qa/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 516,
                  homepageType: 'ADMIN',
                  menuName: 'Q&A 등록  ',
                  parentMenuId: 93,
                  menuUrl: '/education/board/qa/add',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 517,
                  homepageType: 'ADMIN',
                  menuName: 'Q&A 수정  ',
                  parentMenuId: 93,
                  menuUrl: '/education/board/qa/edit/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
            {
              id: 97,
              homepageType: 'ADMIN',
              menuName: 'FAQ',
              parentMenuId: 80,
              menuUrl: '/education/board/faq',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [],
            },
            {
              id: 600,
              homepageType: 'ADMIN',
              menuName: '오류/개선',
              parentMenuId: 80,
              menuUrl: '/education/board/feedback',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 601,
                  homepageType: 'ADMIN',
                  menuName: '오류/개선 상세',
                  parentMenuId: 600,
                  menuUrl: '/education/board/feedback/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 602,
                  homepageType: 'ADMIN',
                  menuName: '오류/개선 등록',
                  parentMenuId: 600,
                  menuUrl: '/education/board/feedback/add',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
                {
                  id: 603,
                  homepageType: 'ADMIN',
                  menuName: '오류/개선 수정',
                  parentMenuId: 600,
                  menuUrl: '/education/board/feedback/edit/[id]',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'document',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                  _children: [],
                },
              ],
            },
          ],
        },
        {
          id: 17,
          homepageType: 'ADMIN',
          menuName: '퍼블리싱 가이드',
          parentMenuId: 1,
          menuUrl: '',
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: false,
          menuIcon: 'graduation-cap',
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [
            {
              id: 18,
              homepageType: 'ADMIN',
              menuName: '기본 디자인',
              parentMenuId: 12,
              menuUrl: '/publish/guide/basic-design',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 19,
              homepageType: 'ADMIN',
              menuName: '폼 공통 요소',
              parentMenuId: 12,
              menuUrl: '/publish/guide/form-common',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 20,
              homepageType: 'ADMIN',
              menuName: '버튼 공통 요소',
              parentMenuId: 12,
              menuUrl: '/publish/guide/button-common',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 21,
              homepageType: 'ADMIN',
              menuName: '공통 UI 컴포넌트',
              parentMenuId: 12,
              menuUrl: '/publish/guide/common-ui',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 22,
              homepageType: 'ADMIN',
              menuName: '공통 모달 컴포넌트',
              parentMenuId: 12,
              menuUrl: '/publish/guide/modal-sample',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 230,
              homepageType: 'ADMIN',
              menuName: '마이슈트 리포팅툴',
              parentMenuId: 12,
              menuUrl: '/publish/guide/mysuit/report',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
          ],
        },
        {
          id: 342,
          homepageType: 'ADMIN',
          menuName: '관리자 디자인 설정',
          parentMenuId: 1,
          menuUrl: '/education/setting/custom',
          menuDepth: 1,
          menuOrder: 0,
          isActive: false,
          requireLogin: true,
          menuType: 'PAGE',
          isNavigation: false,
          menuIcon: null,
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [],
        },
      ];

      return {
        success: true,
        data: menuList,
        message: '메뉴 목록을 성공적으로 조회했습니다.',
      };
    } else {
      throw createError({
        statusCode: 405,
        statusMessage: 'Method Not Allowed',
      });
    }
  } catch (error) {
    console.error('메뉴 목록 조회 중 오류 발생:', error);
    throw createError({
      statusCode: 500,
      statusMessage: 'Internal Server Error',
    });
  }
});
