export default defineEventHandler(async (event) => {
  try {
    if (event.method === 'GET') {
      const menuList = [
        {
          id: 1,
          homepageType: 'ADMIN',
          menuName: '개발 아키텍처',
          parentMenuId: null,
          menuUrl: null,
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: true,
          menuIcon: 'pencil',
          isDeleted: false,
          createdDate: '2025-07-14T13:00:59',
          lastModifiedDate: '2025-07-14T13:02:02',
          _children: [
            {
              id: 2,
              homepageType: 'ADMIN',
              menuName: 'Nuxt 4 + FSD',
              parentMenuId: 1,
              menuUrl: '/architecture/nuxt-fsd',
              menuDepth: 2,
              menuOrder: 1,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [],
            },
            {
              id: 3,
              homepageType: 'ADMIN',
              menuName: '외부 공통 패키지',
              parentMenuId: 1,
              menuUrl: '/architecture/external-common-package',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: true,
              menuIcon: 'pencil',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 4,
                  homepageType: 'ADMIN',
                  menuName: '@wbsoft/ui-overlay',
                  parentMenuId: 3,
                  menuUrl: '/architecture/external-common-package/ui-overlay',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 5,
                  homepageType: 'ADMIN',
                  menuName: '@wbsoft/ui-layout',
                  parentMenuId: 3,
                  menuUrl: '/architecture/external-common-package/ui-layout',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: false,
                  menuIcon: 'pencil',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
          ],
        },
        {
          id: 81,
          homepageType: 'ADMIN',
          menuName: '공통시스템',
          parentMenuId: 1,
          menuUrl: '',
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: false,
          menuIcon: 'common-setting',
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [
            {
              id: 83,
              homepageType: 'ADMIN',
              menuName: '코드관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 84,
                  homepageType: 'ADMIN',
                  menuName: '공통코드관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/code',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: null,
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 85,
              homepageType: 'ADMIN',
              menuName: '권한관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'FOLDER',
              isNavigation: true,
              menuIcon: null,
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
              _children: [
                {
                  id: 86,
                  homepageType: 'ADMIN',
                  menuName: '사용자관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/authority/user',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 870,
                  homepageType: 'ADMIN',
                  menuName: '프로그램관리',
                  parentMenuId: 81,
                  menuUrl: '/education/system/authority/program',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 87,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹관리',
                  parentMenuId: 86,
                  menuUrl: '/education/system/authority/group/management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 88,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹별 프로그램관리',
                  parentMenuId: 86,
                  menuUrl:
                    '/education/system/authority/group/program-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 89,
                  homepageType: 'ADMIN',
                  menuName: '업무그룹별 사용자관리',
                  parentMenuId: 86,
                  menuUrl: '/education/system/authority/group/user-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  menuType: 'PAGE',
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 90,
              homepageType: 'ADMIN',
              menuName: '기타관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              isNavigation: true,
              _children: [
                {
                  id: 91,
                  homepageType: 'ADMIN',
                  menuName: '직무별교육체계도 관리',
                  parentMenuId: 90,
                  menuUrl: '/education/system/etc/job-education-system',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 92,
                  homepageType: 'ADMIN',
                  menuName: '오시는길 관리',
                  parentMenuId: 90,
                  menuUrl: '/education/system/etc/edu-institution',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
            {
              id: 91,
              homepageType: 'ADMIN',
              menuName: '배치관리',
              parentMenuId: 81,
              menuUrl: null,
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              isNavigation: true,
              _children: [
                {
                  id: 91,
                  homepageType: 'ADMIN',
                  menuName: '배치프로그램관리',
                  parentMenuId: 91,
                  menuUrl: '/education/system/batch/program-management',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
                {
                  id: 92,
                  homepageType: 'ADMIN',
                  menuName: '배치결과',
                  parentMenuId: 91,
                  menuUrl: '/education/system/batch/result',
                  menuDepth: 3,
                  menuOrder: 0,
                  isActive: true,
                  requireLogin: true,
                  isNavigation: true,
                  menuIcon: 'common-setting',
                  isDeleted: false,
                  createdDate: '2025-07-14T13:10:40',
                  lastModifiedDate: '2025-07-17T08:54:55',
                },
              ],
            },
          ],
        },
        {
          id: 17,
          homepageType: 'ADMIN',
          menuName: '퍼블리싱 가이드',
          parentMenuId: 1,
          menuUrl: '',
          menuDepth: 1,
          menuOrder: 0,
          isActive: true,
          requireLogin: true,
          menuType: 'FOLDER',
          isNavigation: false,
          menuIcon: 'graduation-cap',
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [
            {
              id: 18,
              homepageType: 'ADMIN',
              menuName: '기본 디자인',
              parentMenuId: 12,
              menuUrl: '/publish/guide/basic-design',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 19,
              homepageType: 'ADMIN',
              menuName: '폼 공통 요소',
              parentMenuId: 12,
              menuUrl: '/publish/guide/form-common',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 20,
              homepageType: 'ADMIN',
              menuName: '버튼 공통 요소',
              parentMenuId: 12,
              menuUrl: '/publish/guide/button-common',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 21,
              homepageType: 'ADMIN',
              menuName: '공통 UI 컴포넌트',
              parentMenuId: 12,
              menuUrl: '/publish/guide/common-ui',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 22,
              homepageType: 'ADMIN',
              menuName: '공통 모달 컴포넌트',
              parentMenuId: 12,
              menuUrl: '/publish/guide/modal-sample',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
            {
              id: 230,
              homepageType: 'ADMIN',
              menuName: '마이슈트 리포팅툴',
              parentMenuId: 12,
              menuUrl: '/publish/guide/mysuit/report',
              menuDepth: 2,
              menuOrder: 0,
              isActive: true,
              requireLogin: true,
              menuType: 'PAGE',
              isNavigation: false,
              menuIcon: 'document',
              isDeleted: false,
              createdDate: '2025-07-14T13:10:40',
              lastModifiedDate: '2025-07-17T08:54:55',
            },
          ],
        },
        {
          id: 342,
          homepageType: 'ADMIN',
          menuName: '관리자 디자인 설정',
          parentMenuId: 1,
          menuUrl: '/setting/custom',
          menuDepth: 1,
          menuOrder: 0,
          isActive: false,
          requireLogin: true,
          menuType: 'PAGE',
          isNavigation: false,
          menuIcon: null,
          isDeleted: false,
          createdDate: '2025-07-14T13:10:40',
          lastModifiedDate: '2025-07-17T08:54:55',
          _children: [],
        },
      ];

      return {
        success: true,
        data: menuList,
        message: '메뉴 목록을 성공적으로 조회했습니다.',
      };
    } else {
      throw createError({
        statusCode: 405,
        statusMessage: 'Method Not Allowed',
      });
    }
  } catch (error) {
    console.error('메뉴 목록 조회 중 오류 발생:', error);
    throw createError({
      statusCode: 500,
      statusMessage: 'Internal Server Error',
    });
  }
});
